## Para praticar os métodos aprendidos no decorrer dessa aula e também aprender novos, vamos realizar alguns tratamentos e seleções utilizando um arquivo csv diferente: alunos.csv.

### Esse arquivo é o mesmo utilizado para resolução dos desafios da aula 1 e 3 e possui dados referentes a alunos de um curso superior. Com base nisso, solucione os problemas propostos abaixo utilizando os conhecimentos adquiridos até aqui.

1) Os alunos participaram de uma atividade extracurricular e ganharam pontos extras. Esses pontos extras correspondem a 40% da nota atual de cada um deles. Com base nisso, crie uma coluna chamada "Pontos_extras" que contenha os pontos extras de cada aluno, ou seja, 40% da nota atual deles.

2) Crie mais uma coluna, chamada "Notas_finais" que possua as notas de cada aluno somada com os pontos extras.

3) Como houve uma pontuação extra, alguns alunos que não tinham sido aprovados antes podem ter sido aprovados agora. Com base nisso, crie uma coluna chamada "Aprovado_final" com os seguintes valores:

- True: caso o aluno esteja aprovado (nota final deve ser maior ou igual a 6);
- False: caso o aluno esteja reprovado (nota final deve ser menor que 6).

4) Faça uma seleção e verifique quais alunos não tinham sido aprovados anteriormente, mas foram aprovados após a soma dos pontos extras.

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv')

df.head()

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True

In [18]:
df['Pontos_extras'] = df['Notas']*0.4

df.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras
0    Ary     20    7.5      True            3.0
1    Ana     18    NaN     False            NaN
2  Cátia     27    2.5     False            1.0
3  Denis     18    5.0     False            2.0
4   Beto     21   10.0      True            4.0

In [19]:
df['Nota_final'] = df['Notas'] + df['Pontos_extras']

df.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras  Nota_final
0    Ary     20    7.5      True            3.0        10.5
1    Ana     18    NaN     False            NaN         NaN
2  Cátia     27    2.5     False            1.0         3.5
3  Denis     18    5.0     False            2.0         7.0
4   Beto     21   10.0      True            4.0        14.0

In [33]:
df['Aprovado_final'] = df['Nota_final'].apply(lambda x: True if x >= 6 else False)

df.head()

    Nome  Idade  Notas  Aprovado  Pontos_extras  Nota_final  Aprovado_final
0    Ary     20    7.5      True            3.0        10.5            True
1    Ana     18    NaN     False            NaN         NaN           False
2  Cátia     27    2.5     False            1.0         3.5           False
3  Denis     18    5.0     False            2.0         7.0            True
4   Beto     21   10.0      True            4.0        14.0            True

In [34]:
df_1 = df[(df['Aprovado']  == False) & (df['Aprovado_final'] == True)]

df_1.head()

     Nome  Idade  Notas  Aprovado  Pontos_extras  Nota_final  Aprovado_final
3   Denis     18    5.0     False           2.00        7.00            True
8   Alice     35    5.6     False           2.24        7.84            True
11   Igor     24    4.5     False           1.80        6.30            True